import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { resolve } from 'path';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  build: {
    outDir: '.',
    lib: {
      entry: resolve(__dirname, 'src/main.ts'),
      name: 'ReviewTagPlugin',
      formats: ['cjs'],
      fileName: () => 'main.js',
    },
    sourcemap: false,
    rollupOptions: {
      external: ['obsidian'],
      output: {
        exports: 'default',
        assetFileNames: (assetInfo) => {
          if (assetInfo.name?.endsWith('.css')) {
            return 'styles.css';
          }
          return assetInfo.name || 'assets/[name].[hash][extname]';
        },
        banner: `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugins github repository
*/
`,
      },
    },
  },
});